set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" NERDtree on github
Plugin 'scrooloose/nerdtree'

" scheme groovebox
Plugin 'morhetz/gruvbox'

" scheme jellybean
Plugin 'nanotech/jellybeans.vim'

" scheme nord
Plugin 'arcticicestudio/nord-vim'

" autoclose parenthesis
Plugin 'Townk/vim-autoclose'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"
" Set number command at start up
set number

" Set tab character that appear 4-spaces-wide
set tabstop=4

" Set syntax highlighting on
syntax on

" Fix scroll bug
syn sync fromstart

" Set colorscheme
colorscheme jellybeans
